// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0z0_KGSV4JOw0bFbcImeLuOqf9jwDROs',
    appId: '1:591098093223:web:2de06b71ba2dbea8d48582',
    messagingSenderId: '591098093223',
    projectId: 'othello-5602d',
    authDomain: 'othello-5602d.firebaseapp.com',
    databaseURL: 'https://othello-5602d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'othello-5602d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdjg1PtHlEMxOZ7fatXFCQTc39pm9fNOE',
    appId: '1:591098093223:android:039be660191b5cc0d48582',
    messagingSenderId: '591098093223',
    projectId: 'othello-5602d',
    databaseURL: 'https://othello-5602d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'othello-5602d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUcSvYmRN6me7_m2Q9HGIL7z1A2bMZ94',
    appId: '1:591098093223:ios:64654d6178822760d48582',
    messagingSenderId: '591098093223',
    projectId: 'othello-5602d',
    databaseURL: 'https://othello-5602d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'othello-5602d.appspot.com',
    iosClientId: '591098093223-uilgqrb955u4657k275qqm3uip7om78l.apps.googleusercontent.com',
    iosBundleId: 'com.example.othello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUcSvYmRN6me7_m2Q9HGIL7z1A2bMZ94',
    appId: '1:591098093223:ios:64654d6178822760d48582',
    messagingSenderId: '591098093223',
    projectId: 'othello-5602d',
    databaseURL: 'https://othello-5602d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'othello-5602d.appspot.com',
    iosClientId: '591098093223-uilgqrb955u4657k275qqm3uip7om78l.apps.googleusercontent.com',
    iosBundleId: 'com.example.othello',
  );
}
